import type { PortfolioData } from '@/types';

export const data: PortfolioData = {
  introduction:
    'Hi! I am Mariana, but you can call me Mari, like all my Brazilian friends do. I’m a Frontend Engineer who recently moved to Melbourne and is currently on a very serious quest for the city’s best tiramisu, usually accompanied by my dog Margot, a Japanese Spitz with a lot of personality. My background in History trained me to research, question, and organize chaos, and now I use those same skills in frontend engineering, turning “what on earth is going on here?” into “oh, this makes sense.” If you want to talk about frontend techniques, tiramisu, or the best dog-friendly coffee spots in Melbourne, 🩷 I’d love to connect!',
  projects: [
    {
      id: 'fit-my-space',
      title: 'Fit My Space',
      description:
        "Developed a sleek and intuitive single-page application that serves as a complete digital address book. The project focuses on a smooth user experience, allowing you to easily add new contacts, favorite the people you talk to most, and keep your entire list organized with full update and display capabilities. To support the project's long-term scalability, I am also engineering an ongoing, custom Core Design System built from the ground up. This system bridges design tokens via Style Dictionary with accessible primitives, ensuring WCAG compliance without compromising the product's clean aesthetics.",
      technologies: [
        'React',
        'Typescript',
        'Tailwind CSS',
        'Next.js',
        'TanStack Query',
        'Jest',
        'Vitest',
        'React Testing Library',
        'Atomic Design',
        'Axe',
        'Radix Primitives',
        'Style Dictionary',
        'Storybook',
      ],
      githubUrl: 'https://github.com/mariana-martins/FitMySpace',
    },
    {
      id: 'frontend-practice-abstract',
      title: 'Frontend Practice Abstract',
      description:
        "It is a fully responsive, pixel-perfect implementation of the original Abstract design. It features a clean, modular component architecture and a functional search interface, ensuring a seamless experience whether you're on a desktop or a mobile phone.",
      technologies: [
        'React',
        'Vite',
        'Styled Components',
        'Jest',
        'React Testing Library',
        'Axe',
        'Radix Primitives',
      ],
      githubUrl:
        'https://github.com/mariana-martins/frontend-practice-abstract',
    },
    {
      id: 'contact-app',
      title: 'Contact App',
      description:
        'The goal here is to implement an App to lets a user play the Would You Rather? game. A question is displayed and a user needs answer it. It was developed using React, Redux and Material UI.',
      technologies: ['React', 'Javascript', 'React Router', 'Material UI'],
      githubUrl: 'https://github.com/mariana-martins/contact-app',
    },
  ],
  experience: [
    {
      id: 'health-and-well-being-career-break',
      company: 'Career Break',
      position: 'Health and well-being',
      startDate: '2024-05',
      endDate: undefined, // ongoing
      description:
        'Stepped away from full-time work for health recovery while building continuously. Designed FitMySpace in Next.js, TypeScript, and TanStack Query, owning a Style Dictionary token pipeline end to end, plus a design system on Radix Primitives and Storybook. Used Claude and Gemini to generate components from design specs, validating each for accessibility and performance.',
      technologies: [
        'React',
        'TypeScript',
        'Next.js',
        'TanStack Query',
        'Style Dictionary',
        'Design Tokens',
        'Radix UI',
        'Storybook',
        'Tailwind CSS',
        'CSS Modules',
        'Vite',
        'Motion',
        'Penpot',
        'Claude',
        'Gemini',
        'Atomic Design',
      ],
    },
    {
      id: 'remote-frontend-engineer',
      company: 'Remote',
      website: 'https://remote.com',
      position: 'Frontend Engineer',
      startDate: '2021-07',
      endDate: '2024-04',
      description:
        "Built B2B onboarding flows for Remote's global Employer of Record platform with React, TypeScript, Next.js, and TanStack Query. Migrated legislation-aware forms from Formik to a backend-owned JSON Schema architecture, root-caused production incidents in Sentry and Datadog, and worked on the Accessibility team toward WCAG 2.1 compliance.",
      technologies: [
        'React',
        'TypeScript',
        'Next.js',
        'TanStack Query',
        'Styled Components',
        'JSON Schema',
        'Storybook',
        'Jest',
        'React Testing Library',
        'Cypress',
        'GitLab CI/CD',
        'AWS',
        'Sentry',
        'Datadog',
        'WCAG 2.1',
      ],
    },
    {
      id: 'phocas-software-developer',
      company: 'Phocas Software',
      website: 'https://www.phocassoftware.com/',
      position: 'Frontend Developer',
      startDate: '2021-01',
      endDate: '2021-06',
      description:
        "Promoted to Frontend Developer within ten months, recognised for the frontend experience work on Budgeting & Forecasting. Acted as the bridge between design and engineering on the Financial Statements flagship, designing components in Figma and architecting their implementation, and built the company's first Design System in React, Material UI, and Storybook.",
      technologies: [
        'React',
        'TypeScript',
        'Material UI',
        'Figma',
        'Storybook',
        'Design Tokens',
        'MobX',
        'Jest',
        'React Testing Library',
      ],
    },
    {
      id: 'phocas-junior-software-developer',
      company: 'Phocas Software',
      website: 'https://www.phocassoftware.com/',
      position: 'Junior Frontend Developer',
      startDate: '2020-03',
      endDate: '2021-01',
      description:
        "Led the frontend experience and layout for the flagship Budgeting & Forecasting module, pairing with the product designer and presenting the result to the company's founders. Built a high-performance data grid end to end in React, TypeScript, MobX, and Apollo GraphQL, and introduced a Jest and React Testing Library suite that cut production defects.",
      technologies: [
        'React',
        'TypeScript',
        'MobX',
        'GraphQL',
        'Apollo',
        'Material UI',
        'Jest',
        'React Testing Library',
        'Redux',
        'Figma',
      ],
    },
    {
      id: 'kathmandu-junior-frontend',
      company: 'Kathmandu',
      website: 'https://www.kathmandu.co.nz/',
      position: 'Junior Frontend Developer',
      startDate: '2018-10',
      endDate: '2020-03',
      description:
        'Engineered high-performance e-commerce interfaces for a leading AU/UK/NZ retail platform on Magento 2, improving the customer journey and conversion rates. Built responsive components in HTML5, CSS3, and jQuery with cross-browser compatibility and mobile-first performance.',
      technologies: [
        'Magento 2',
        'HTML5',
        'CSS3',
        'JavaScript',
        'jQuery',
        'Responsive Design',
        'Figma',
        'Google Tag Manager',
      ],
    },
  ],
  skills: [
    {
      name: 'HTML5',
      level: 'expert',
      category: 'frontend',
    },
    {
      name: 'CSS3',
      level: 'expert',
      category: 'frontend',
    },
    {
      name: 'JavaScript',
      level: 'expert',
      category: 'frontend',
    },
    {
      name: 'React',
      level: 'expert',
      category: 'frontend',
    },
    {
      name: 'TypeScript',
      level: 'intermediate',
      category: 'frontend',
    },
    {
      name: 'Redux',
      level: 'intermediate',
      category: 'frontend',
    },
    {
      name: 'Sass',
      level: 'intermediate',
      category: 'frontend',
    },
    {
      name: 'Bootstrap',
      level: 'intermediate',
      category: 'frontend',
    },
    {
      name: 'Material UI',
      level: 'advanced',
      category: 'frontend',
    },
    {
      name: 'Styled Components',
      level: 'advanced',
      category: 'frontend',
    },
    {
      name: 'jQuery',
      level: 'intermediate',
      category: 'frontend',
    },
    {
      name: 'Mobx',
      level: 'intermediate',
      category: 'frontend',
    },
    {
      name: 'React Query',
      level: 'intermediate',
      category: 'frontend',
    },
    {
      name: 'Jest',
      level: 'intermediate',
      category: 'tools',
    },
    {
      name: 'React Testing Library',
      level: 'intermediate',
      category: 'tools',
    },
    {
      name: 'Enzyme',
      level: 'beginner',
      category: 'tools',
    },
    {
      name: 'Webpack',
      level: 'beginner',
      category: 'tools',
    },
    {
      name: 'Figma',
      level: 'intermediate',
      category: 'design',
    },
    {
      name: 'Adobe Photoshop',
      level: 'beginner',
      category: 'design',
    },
    {
      name: 'Storybook',
      level: 'intermediate',
      category: 'tools',
    },
    {
      name: 'Tailwind CSS',
      level: 'beginner',
      category: 'frontend',
    },
    {
      name: 'Motion',
      level: 'beginner',
      category: 'frontend',
    },
    {
      name: 'Vite',
      level: 'beginner',
      category: 'tools',
    },
    {
      name: 'Next.js',
      level: 'intermediate',
      category: 'frontend',
    },
    {
      name: 'Atomic Design',
      level: 'intermediate',
      category: 'design',
    },
    {
      name: 'Radix Primitives',
      level: 'beginner',
      category: 'frontend',
    },
    {
      name: 'Axe',
      level: 'beginner',
      category: 'tools',
    },
    {
      name: 'React Router',
      level: 'beginner',
      category: 'frontend',
    },
  ],
  funFacts: [
    {
      id: 'fun-fact-1',
      question: 'How many countries have I called "home" so far?',
      fact: 'Three! Brazil, New Zealand, and now Australia. I’m basically collecting countries like side quests and XP.',
    },
    {
      id: 'fun-fact-2',
      question: 'What is my quirky collection hobby?',
      fact: 'Gel pens! I have one for every mood, occasion, and minor life crisis. Digital code is great, but physical ink is a vibe.',
    },
    {
      id: 'fun-fact-3',
      question:
        'What is my favorite way to "build" things when I’m away from a computer screen?',
      fact: 'LEGO! My shelves are home to a wild mix including the Simpsons House, the Yellow Submarine, and Rivendell. Up next? Conquering Sauron’s Tower and Bag End brick by brick.',
    },
    {
      id: 'fun-fact-4',
      question:
        'Which movie franchise have I watched an "unreasonable" number of times?',
      fact: 'The Lord of the Rings! (Extended editions only, obviously). I can navigate the path to Mount Doom better than a GPS.',
    },
    {
      id: 'fun-fact-5',
      question: 'What book changed my perspective on life?',
      fact: 'Untamed by Glennon Doyle. It’s the book that taught me to trust my intuition and never apologize for being exactly who I am.',
    },
    {
      id: 'fun-fact-6',
      question: 'How do I stay grounded between intense coding sessions?',
      fact: 'Tai Chi! It’s my favorite way to slow down and find my "zen" when life gets a little too fast.',
    },
  ],
  contact: {
    name: 'Mariana Martins Menezes',
    email: 'marianamartinsmenezes@gmail.com',
    linkedIn: 'https://www.linkedin.com/in/marianamenezes/',
    github: 'https://github.com/mariana-martins', // TODO: Verify GitHub URL
    address: 'Melbourne, Australia',
  },
  learningShelf: [
    {
      id: 'ai-and-design-systems',
      title: 'AI and Design Systems',
      author: 'Brad Frost',
      category: 'course',
      status: 'in-progress',
      link: 'https://aianddesign.systems/',
    },
    {
      id: 'subatomic',
      title: 'Subatomic: The Complete Guide To Design Tokens',
      author: 'Brad Frost',
      category: 'course',
      status: 'completed',
      link: 'https://bradfrost.com/blog/post/introducing-subatomic-the-complete-guide-to-design-tokens/',
    },
    {
      id: 'total-typescript',
      title: 'Total Typescript',
      author: 'Matt Pocock',
      category: 'course',
      status: 'in-progress',
      link: 'https://www.totaltypescript.com/',
    },
    {
      id: 'design-systems',
      title:
        'Design Systems: A practical guide to creating design languages for digital products',
      author: 'Alla Kholmatova',
      category: 'book',
      status: 'planned',
      link: 'https://www.smashingmagazine.com/design-systems-book/',
    },
    {
      id: 'give-and-take',
      title: 'Give and Take: Why Helping Others Drives Success',
      author: 'Adam Grant',
      category: 'book',
      status: 'planned',
      link: 'https://adamgrant.net/book/give-and-take/',
    },
  ],
};
